### PR TITLE
fix: creating literal from falsy literal value

### LINKED ISSUE #22: Cannot easily create "false"^^xsd:boolean literal
Calling `cf.literal(false)` does not return a new clownface instance

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #22

### CODE REVIEW

File: lib/toTermArray.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ const term = require('./term')
 const toArray = require('./toArray')
 
 function toTermArray (items, type, languageOrDatatype) {
-  if (!items && !type) {
+  if (items !== false && !items && !type) {
```
Comment (thewilkybarkid) [inline lib/toTermArray.js]: Related, `!items` also creates a problem with `0` (refs https://github.com/libero/article-store/blob/c4f460169e4a58159a7b99ec0e52ee2a7c83e15d/src/routes/article-list.ts#L30).

Should the check be like https://github.com/rdf-ext/clownface/pull/18?

**Comment by tpluscode** [comment]
I applied the suggestion from @thewilkybarkid and added tests for the cases of empty string and `0`. 

By checking explicitly for `null` and `undefined` any other falsy value will create a literal. An empty array is also implicitly handled to not create pointers. I think that's correct.
